project_id = "ujomaaiszjaybxaerqhq"

[functions.generate-itinerary]
verify_jwt = true

[functions.get-shared-data]
verify_jwt = false

[functions.generate-letter]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
