import { Info } from 'lucide-react';

type Variant = 'discover' | 'discover-ai' | 'itinerary' | 'summary';

const MESSAGES: Record<Variant, string> = {
  discover:
    'Places are sourced from OpenStreetMap contributors and described by AI. Information may be incomplete, inaccurate, or outdated — always verify opening hours, admission, and access independently before visiting.',
  'discover-ai':
    'OpenStreetMap data was sparse for this area. These recommendations are based on AI training knowledge and may not reflect current conditions or exact locations. Always verify before visiting.',
  itinerary:
    'This itinerary was generated by AI and may contain inaccuracies. Verify all bookings, opening hours, admission prices, and transport details independently before your trip. Website and booking links are provided by AI and may be incorrect.',
  summary:
    'Generated by AI from your logged visit data. Descriptions are AI interpretations and may not perfectly reflect your actual experiences.',
};

interface AiDisclaimerProps {
  variant: Variant;
  className?: string;
}

export function AiDisclaimer({ variant, className }: AiDisclaimerProps) {
  return (
    <div className={`flex items-start gap-2 p-3 rounded-lg bg-muted/20 border border-border/40 ${className ?? ''}`}>
      <Info className="w-3.5 h-3.5 text-muted-foreground/70 shrink-0 mt-0.5" />
      <p className="text-xs text-muted-foreground/80 leading-relaxed">{MESSAGES[variant]}</p>
    </div>
  );
}
