INSERT INTO public.countries (iso2, name, continent, flag_primary_color)
VALUES
  ('DZ', 'Algeria', 'Africa', '#006233'),
  ('AO', 'Angola', 'Africa', '#CC092F'),
  ('BJ', 'Benin', 'Africa', '#008751'),
  ('BW', 'Botswana', 'Africa', '#75AADB'),
  ('BF', 'Burkina Faso', 'Africa', '#EF2B2D'),
  ('BI', 'Burundi', 'Africa', '#1EB53A'),
  ('CV', 'Cabo Verde', 'Africa', '#003893'),
  ('CM', 'Cameroon', 'Africa', '#007A5E'),
  ('CF', 'Central African Republic', 'Africa', '#003082'),
  ('TD', 'Chad', 'Africa', '#002664'),
  ('KM', 'Comoros', 'Africa', '#3A75C4'),
  ('CG', 'Congo', 'Africa', '#009543'),
  ('CD', 'Congo (DRC)', 'Africa', '#007FFF'),
  ('CI', 'Côte d''Ivoire', 'Africa', '#F77F00'),
  ('DJ', 'Djibouti', 'Africa', '#6AB2E7'),
  ('EG', 'Egypt', 'Africa', '#C8102E'),
  ('GQ', 'Equatorial Guinea', 'Africa', '#3E9A00'),
  ('ER', 'Eritrea', 'Africa', '#4189DD'),
  ('SZ', 'Eswatini', 'Africa', '#3E5EB9'),
  ('ET', 'Ethiopia', 'Africa', '#078930'),
  ('GA', 'Gabon', 'Africa', '#009E60'),
  ('GM', 'Gambia', 'Africa', '#CE1126'),
  ('GH', 'Ghana', 'Africa', '#006B3F'),
  ('GN', 'Guinea', 'Africa', '#CE1126'),
  ('GW', 'Guinea-Bissau', 'Africa', '#CE1126'),
  ('KE', 'Kenya', 'Africa', '#006600'),
  ('LS', 'Lesotho', 'Africa', '#00209F'),
  ('LR', 'Liberia', 'Africa', '#002868'),
  ('LY', 'Libya', 'Africa', '#239E46'),
  ('MG', 'Madagascar', 'Africa', '#FC3D32'),
  ('MW', 'Malawi', 'Africa', '#000000'),
  ('ML', 'Mali', 'Africa', '#14B53A'),
  ('MR', 'Mauritania', 'Africa', '#006233'),
  ('MU', 'Mauritius', 'Africa', '#EA2839'),
  ('MA', 'Morocco', 'Africa', '#C1272D'),
  ('MZ', 'Mozambique', 'Africa', '#007168'),
  ('NA', 'Namibia', 'Africa', '#003580'),
  ('NE', 'Niger', 'Africa', '#E05206'),
  ('NG', 'Nigeria', 'Africa', '#008751'),
  ('RW', 'Rwanda', 'Africa', '#20603D'),
  ('ST', 'São Tomé and Príncipe', 'Africa', '#12AD2B'),
  ('SN', 'Senegal', 'Africa', '#00853F'),
  ('SC', 'Seychelles', 'Africa', '#003F87'),
  ('SL', 'Sierra Leone', 'Africa', '#1EB53A'),
  ('SO', 'Somalia', 'Africa', '#4189DD'),
  ('ZA', 'South Africa', 'Africa', '#007A4D'),
  ('SS', 'South Sudan', 'Africa', '#078930'),
  ('SD', 'Sudan', 'Africa', '#D21034'),
  ('TZ', 'Tanzania', 'Africa', '#1EB53A'),
  ('TG', 'Togo', 'Africa', '#006A4E'),
  ('TN', 'Tunisia', 'Africa', '#E70013'),
  ('UG', 'Uganda', 'Africa', '#FCDC04'),
  ('ZM', 'Zambia', 'Africa', '#198A00'),
  ('ZW', 'Zimbabwe', 'Africa', '#006400'),
  ('AF', 'Afghanistan', 'Asia', '#000000'),
  ('AM', 'Armenia', 'Asia', '#D90012'),
  ('AZ', 'Azerbaijan', 'Asia', '#3F9C35'),
  ('BH', 'Bahrain', 'Asia', '#CE1126'),
  ('BD', 'Bangladesh', 'Asia', '#006A4E'),
  ('BT', 'Bhutan', 'Asia', '#FF4E12'),
  ('BN', 'Brunei', 'Asia', '#F7E017'),
  ('KH', 'Cambodia', 'Asia', '#032EA1'),
  ('CN', 'China', 'Asia', '#DE2910'),
  ('CY', 'Cyprus', 'Asia', '#D57800'),
  ('GE', 'Georgia', 'Asia', '#FF0000'),
  ('IN', 'India', 'Asia', '#FF9933'),
  ('ID', 'Indonesia', 'Asia', '#FF0000'),
  ('IR', 'Iran', 'Asia', '#239F40'),
  ('IQ', 'Iraq', 'Asia', '#CE1126'),
  ('IL', 'Israel', 'Asia', '#0038B8'),
  ('JP', 'Japan', 'Asia', '#BC002D'),
  ('JO', 'Jordan', 'Asia', '#007A3D'),
  ('KZ', 'Kazakhstan', 'Asia', '#00AFCA'),
  ('KW', 'Kuwait', 'Asia', '#007A3D'),
  ('KG', 'Kyrgyzstan', 'Asia', '#E8112D'),
  ('LA', 'Laos', 'Asia', '#CE1126'),
  ('LB', 'Lebanon', 'Asia', '#ED1C24'),
  ('MY', 'Malaysia', 'Asia', '#010066'),
  ('MV', 'Maldives', 'Asia', '#D21034'),
  ('MN', 'Mongolia', 'Asia', '#C4272F'),
  ('MM', 'Myanmar', 'Asia', '#FECB00'),
  ('NP', 'Nepal', 'Asia', '#DC143C'),
  ('KP', 'North Korea', 'Asia', '#ED1C27'),
  ('OM', 'Oman', 'Asia', '#DB161B'),
  ('PK', 'Pakistan', 'Asia', '#01411C'),
  ('PS', 'Palestine', 'Asia', '#007A3D'),
  ('PH', 'Philippines', 'Asia', '#0038A8'),
  ('QA', 'Qatar', 'Asia', '#8D1B3D'),
  ('SA', 'Saudi Arabia', 'Asia', '#006C35'),
  ('SG', 'Singapore', 'Asia', '#EF3340'),
  ('KR', 'South Korea', 'Asia', '#003478'),
  ('LK', 'Sri Lanka', 'Asia', '#8D153A'),
  ('SY', 'Syria', 'Asia', '#CE1126'),
  ('TW', 'Taiwan', 'Asia', '#FE0000'),
  ('TJ', 'Tajikistan', 'Asia', '#006600'),
  ('TH', 'Thailand', 'Asia', '#241D4F'),
  ('TL', 'Timor-Leste', 'Asia', '#DC241F'),
  ('TR', 'Turkey', 'Asia', '#E30A17'),
  ('TM', 'Turkmenistan', 'Asia', '#28AE66'),
  ('AE', 'United Arab Emirates', 'Asia', '#00732F'),
  ('UZ', 'Uzbekistan', 'Asia', '#1EB53A'),
  ('VN', 'Vietnam', 'Asia', '#DA251D'),
  ('YE', 'Yemen', 'Asia', '#CE1126'),
  ('AL', 'Albania', 'Europe', '#E41E20'),
  ('AD', 'Andorra', 'Europe', '#0032A0'),
  ('AT', 'Austria', 'Europe', '#ED2939'),
  ('BY', 'Belarus', 'Europe', '#C8313E'),
  ('BE', 'Belgium', 'Europe', '#000000'),
  ('BA', 'Bosnia and Herzegovina', 'Europe', '#002395'),
  ('BG', 'Bulgaria', 'Europe', '#00966E'),
  ('HR', 'Croatia', 'Europe', '#FF0000'),
  ('CZ', 'Czech Republic', 'Europe', '#11457E'),
  ('DK', 'Denmark', 'Europe', '#C8102E'),
  ('EE', 'Estonia', 'Europe', '#0072CE'),
  ('FI', 'Finland', 'Europe', '#003580'),
  ('FR', 'France', 'Europe', '#0055A4'),
  ('DE', 'Germany', 'Europe', '#000000'),
  ('GR', 'Greece', 'Europe', '#0D5EAF'),
  ('HU', 'Hungary', 'Europe', '#436F4D'),
  ('IS', 'Iceland', 'Europe', '#02529C'),
  ('IE', 'Ireland', 'Europe', '#169B62'),
  ('IT', 'Italy', 'Europe', '#009246'),
  ('XK', 'Kosovo', 'Europe', '#244AA5'),
  ('LV', 'Latvia', 'Europe', '#9E3039'),
  ('LI', 'Liechtenstein', 'Europe', '#002B7F'),
  ('LT', 'Lithuania', 'Europe', '#006A44'),
  ('LU', 'Luxembourg', 'Europe', '#00A1DE'),
  ('MT', 'Malta', 'Europe', '#CF142B'),
  ('MD', 'Moldova', 'Europe', '#003DA5'),
  ('MC', 'Monaco', 'Europe', '#CE1126'),
  ('ME', 'Montenegro', 'Europe', '#C40308'),
  ('NL', 'Netherlands', 'Europe', '#AE1C28'),
  ('MK', 'North Macedonia', 'Europe', '#D20000'),
  ('NO', 'Norway', 'Europe', '#BA0C2F'),
  ('PL', 'Poland', 'Europe', '#DC143C'),
  ('PT', 'Portugal', 'Europe', '#006600'),
  ('RO', 'Romania', 'Europe', '#002B7F'),
  ('RU', 'Russia', 'Europe', '#0039A6'),
  ('SM', 'San Marino', 'Europe', '#5EB6E4'),
  ('RS', 'Serbia', 'Europe', '#C6363C'),
  ('SK', 'Slovakia', 'Europe', '#0B4EA2'),
  ('SI', 'Slovenia', 'Europe', '#005DA4'),
  ('ES', 'Spain', 'Europe', '#AA151B'),
  ('SE', 'Sweden', 'Europe', '#006AA7'),
  ('CH', 'Switzerland', 'Europe', '#FF0000'),
  ('UA', 'Ukraine', 'Europe', '#0057B7'),
  ('GB', 'United Kingdom', 'Europe', '#00247D'),
  ('VA', 'Vatican City', 'Europe', '#FFE000'),
  ('AG', 'Antigua and Barbuda', 'North America', '#CE1126'),
  ('BS', 'Bahamas', 'North America', '#00778B'),
  ('BB', 'Barbados', 'North America', '#00267F'),
  ('BZ', 'Belize', 'North America', '#003F87'),
  ('CA', 'Canada', 'North America', '#FF0000'),
  ('CR', 'Costa Rica', 'North America', '#002B7F'),
  ('CU', 'Cuba', 'North America', '#002A8F'),
  ('DM', 'Dominica', 'North America', '#006B3F'),
  ('DO', 'Dominican Republic', 'North America', '#002D62'),
  ('SV', 'El Salvador', 'North America', '#0F47AF'),
  ('GD', 'Grenada', 'North America', '#CE1126'),
  ('GT', 'Guatemala', 'North America', '#4997D0'),
  ('HT', 'Haiti', 'North America', '#00209F'),
  ('HN', 'Honduras', 'North America', '#0073CF'),
  ('JM', 'Jamaica', 'North America', '#009B3A'),
  ('MX', 'Mexico', 'North America', '#006847'),
  ('NI', 'Nicaragua', 'North America', '#0067C6'),
  ('PA', 'Panama', 'North America', '#005293'),
  ('KN', 'Saint Kitts and Nevis', 'North America', '#009E49'),
  ('LC', 'Saint Lucia', 'North America', '#65CFFF'),
  ('VC', 'Saint Vincent and the Grenadines', 'North America', '#0072C6'),
  ('TT', 'Trinidad and Tobago', 'North America', '#CE1126'),
  ('US', 'United States', 'North America', '#3C3B6E'),
  ('AR', 'Argentina', 'South America', '#75AADB'),
  ('BO', 'Bolivia', 'South America', '#007934'),
  ('BR', 'Brazil', 'South America', '#009C3B'),
  ('CL', 'Chile', 'South America', '#0039A6'),
  ('CO', 'Colombia', 'South America', '#FCD116'),
  ('EC', 'Ecuador', 'South America', '#FFD100'),
  ('GY', 'Guyana', 'South America', '#009E49'),
  ('PY', 'Paraguay', 'South America', '#0038A8'),
  ('PE', 'Peru', 'South America', '#D91023'),
  ('SR', 'Suriname', 'South America', '#377E3F'),
  ('UY', 'Uruguay', 'South America', '#0038A8'),
  ('VE', 'Venezuela', 'South America', '#CF142B'),
  ('AU', 'Australia', 'Oceania', '#00008B'),
  ('FJ', 'Fiji', 'Oceania', '#68BFE5'),
  ('KI', 'Kiribati', 'Oceania', '#CE1126'),
  ('MH', 'Marshall Islands', 'Oceania', '#003893'),
  ('FM', 'Micronesia', 'Oceania', '#75B2DD'),
  ('NR', 'Nauru', 'Oceania', '#002B7F'),
  ('NZ', 'New Zealand', 'Oceania', '#00247D'),
  ('PW', 'Palau', 'Oceania', '#4AADD6'),
  ('PG', 'Papua New Guinea', 'Oceania', '#CE1126'),
  ('WS', 'Samoa', 'Oceania', '#CE1126'),
  ('SB', 'Solomon Islands', 'Oceania', '#0051BA'),
  ('TO', 'Tonga', 'Oceania', '#C10000'),
  ('TV', 'Tuvalu', 'Oceania', '#00247D'),
  ('VU', 'Vanuatu', 'Oceania', '#009543')
ON CONFLICT (iso2) DO NOTHING;
